package com.covide.enums;

public enum StatusMasterCodes {
	IN, SD, SI, SF, SL, SC, EDOROD, DINR, RASD, RRSD, DIN, DU, SU, ACTIVE, INACTIVE, APPROVED, STUDINFORMATION,
	INREVIEW,REVIEWED,REJECTED,DATAENTRY,SENDTORIVEW,REJCTED, 
	GR, ACTITYORCRF, AMBULATORY, TOTAL,ACTIVITYWEIGHTFROM
	
}
